#!/system/bin/sh

######### DEBIAN CHROOT LOGIN SHELL #########
SELF_PATH=$(readlink -f "$0")
. "${SELF_PATH%/*}/bootroot_env"

exec $BUSYBOX chroot "$MNT" /usr/bin/env -i \
    HOME=/root \
    USER=root \
    LOGNAME=root \
    SHELL="$CHROOT_SHELL" \
    TERM="${TERM:-xterm-256color}" \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH="$CHROOT_PATH" \
    "$CHROOT_SHELL" -l
